### ISSUE TITLE
天气问题

### ISSUE THREAD

**Issue by axh2018** [shw2018/hexo-blog-fly#8]
又是我，我又来了。
![image](https://user-images.githubusercontent.com/58505743/70863577-86724000-1f84-11ea-9845-72df0cd2b6e0.png)
如图,鼠标放在天气上不会显示具体信息。这个怎么解决呢？

**Comment by shw2018** [comment]
把它放在顶层。

**Comment by axh2018** [comment]
怎么改呢？
把主题配置文件中的weather&nbsp; &nbsp;true移上去吗？
 
---原始邮件---
发件人: "Hongwei Sun"<notifications@github.com&gt;
发送时间: 2019年12月16日 18:37:01
收件人: "shw2018/hexo-blog-fly"<hexo-blog-fly@noreply.github.com&gt;;
抄送: "陈小虎"<3442248990@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [shw2018/hexo-blog-fly] 天气问题 (#8)



把它放在顶层。
